<?php

namespace developermarius\applebusinessconnect\api\models;

/**
 * @see https://businessconnect.apple.com/docs/data-specification/v1.3/location/optional#location-attributes
 */
enum AppleLocationAttributeType: string implements \JsonSerializable
{
    case CROSSBUSINESS = 'crossbusiness';//Cross business refers to the amenities that are applicable across different businesses.
    case CROSSBUSINESS_ACCESSIBILITY_FEATURES = 'crossbusiness.accessibility_features';//Accessibility features mean that the business/establishment has features or facilities to help people with disabilities.
    case CROSSBUSINESS_ACCESSIBILITY_FEATURES_ACCESSIBLE_ELEVATOR = 'crossbusiness.accessibility_features.accessible_elevator';//Accessible elevator means that the elevator has features that support a person with visual, hearing, or physical impairments when using the elevator.
    case CROSSBUSINESS_ACCESSIBILITY_FEATURES_DIGITAL_ACCESSIBILITY = 'crossbusiness.accessibility_features.digital_accessibility';//Digital features supporting people with a visual, auditory, or physical impairment.
    case CROSSBUSINESS_ACCESSIBILITY_FEATURES_MOBILITY_SCOOTER_RENTAL = 'crossbusiness.accessibility_features.mobility_scooter_rental';//A business offering mobility scooters on rent for people with mobility deficits.
    case CROSSBUSINESS_ACCESSIBILITY_FEATURES_WHEELCHAIR_ACCESSIBLE = 'crossbusiness.accessibility_features.wheelchair_accessible';//Wheelchair Accessible refers to the facility indicating that the business or a location is accessible by a wheelchair.
    case CROSSBUSINESS_AGE_RESTRICTIONS = 'crossbusiness.age_restrictions';//Age restriction refers to the age limit or age allowed of the person.
    case CROSSBUSINESS_AGE_RESTRICTIONS_ADULTS_ONLY = 'crossbusiness.age_restrictions.adults_only';//Adults only mean that persons under the age of 18 are not allowed. Or persons over the age of 18 are allowed.
    case CROSSBUSINESS_AGE_RESTRICTIONS_ALL_AGES = 'crossbusiness.age_restrictions.all_ages';//No restrictions means that persons of all ages are welcome.
    case CROSSBUSINESS_AGE_RESTRICTIONS_OVER_16 = 'crossbusiness.age_restrictions.over_16';//Over 16 means, children under the age of 16 are not allowed.
    case CROSSBUSINESS_AGE_RESTRICTIONS_OVER_21 = 'crossbusiness.age_restrictions.over_21';//Over 21 mean that persons under the age of 21 are not allowed.
    case CROSSBUSINESS_AMBIANCE = 'crossbusiness.ambiance';//Ambiance refers to the character or atmosphere of an establishment or business.
    case CROSSBUSINESS_AMBIANCE_CASUAL = 'crossbusiness.ambiance.casual';//Casual ambiance refers to the relaxed and comfortable atmosphere of an establishment or business.
    case CROSSBUSINESS_AMBIANCE_ROMANTIC = 'crossbusiness.ambiance.romantic';//Romantic ambiance refers to the atmosphere of an establishment or business that has soft music, candle light, and other facilities to make the time spent special.
    case CROSSBUSINESS_AMBIANCE_TRADITIONAL = 'crossbusiness.ambiance.traditional';//Traditional ambiance refers to a particular belief or custom atmosphere of an establishment or business.
    case CROSSBUSINESS_AMBIANCE_TRENDY = 'crossbusiness.ambiance.trendy';//Trendy ambiance refers to the fashionable or up to date atmosphere of an establishment or business.
    case CROSSBUSINESS_AMBIANCE_UPSCALE = 'crossbusiness.ambiance.upscale';//Upscale ambiance refers to an expensive and high standard atmosphere or service of an establishment or business.
    case CROSSBUSINESS_ATTIRE = 'crossbusiness.attire';//Attire refers to wearing a specific type of clothes.
    case CROSSBUSINESS_ATTIRE_BIZCASUAL = 'crossbusiness.attire.bizcasual';//Business Casual attire refers to everyday easy formal clothes including footwear that cover all or most of the foot.
    case CROSSBUSINESS_ATTIRE_CASUAL_ATTIRE = 'crossbusiness.attire.casual_attire';//Casual Attire refers to the clothes that are relaxed and suited for everyday wear.
    case CROSSBUSINESS_ATTIRE_ELEGANT = 'crossbusiness.attire.elegant';//Elegant attire refers to clothes that are pleasingly stylish in appearance.
    case CROSSBUSINESS_ATTIRE_FORMAL = 'crossbusiness.attire.formal';//Formal attire refers to fancy clothes that can be traditional/western style while following rules of convention and are suitable for an official or important occasion.
    case CROSSBUSINESS_BARSERVICE = 'crossbusiness.barservice';//Bar service is the facility where non-alcoholic, alcoholic drinks and other condiments are available.
    case CROSSBUSINESS_BARSERVICE_BAR_LOUNGE = 'crossbusiness.barservice.bar_lounge';//The bar lounge is the facility where non-alcoholic, alcoholic drinks and other condiments are available in a room with comfortable tables and sittings.
    case CROSSBUSINESS_BARSERVICE_BEER_WINE = 'crossbusiness.barservice.beer_wine';//Beer and wine is the facility where only beer and wines are available.
    case CROSSBUSINESS_BARSERVICE_BYOB = 'crossbusiness.barservice.byob';//Business attribute for Bring Your Own Booze, meaning the customer can bring their own alcohol.
    case CROSSBUSINESS_BARSERVICE_BYOB_CORKAGE_FEE = 'crossbusiness.barservice.byob.corkage_fee';//Business that charges a corkage fee for opening a customer brought bottle of alcohol.
    case CROSSBUSINESS_BARSERVICE_BYOB_CORKAGE_FREE = 'crossbusiness.barservice.byob.corkage_free';//Corkage Free means that the establishment does not charge a fee from the dining customers when they bring their own beverage.
    case CROSSBUSINESS_BARSERVICE_FULLBAR = 'crossbusiness.barservice.fullbar';//Full bar is the facility where variety of non-alcoholic, alcoholic drinks and other condiments are available.
    case CROSSBUSINESS_BARSERVICE_HAPPYHOUR = 'crossbusiness.barservice.happyhour';//Happy Hour refers that the establishment offers discounted or free meals and/or alcoholic drinks, appetizers, etc. during certain hours to its customers.
    case CROSSBUSINESS_BARSERVICE_NO_ALCOHOL = 'crossbusiness.barservice.no_alcohol';//Business that does not serve alcohol.
    case CROSSBUSINESS_BIZMODELS = 'crossbusiness.bizmodels';//Business models refers to the establishment’s ownership and management.
    case CROSSBUSINESS_BIZMODELS_CO_OP = 'crossbusiness.bizmodels.co_op';//The establishment operates in an co-operative business.
    case CROSSBUSINESS_BIZMODELS_MEMBERSHIP_REQUIRED = 'crossbusiness.bizmodels.membership_required';//An establishment where a membership is required to enter or use a facility.
    case CROSSBUSINESS_BIZMODELS_NONPROFIT = 'crossbusiness.bizmodels.nonprofit';//The establishment is a non-profit business.
    case CROSSBUSINESS_CELLPHONE_RENTAL = 'crossbusiness.cellphone_rental';//An establishment or a business offering cell phones on rent to their guests or visitors.
    case CROSSBUSINESS_CLASSES = 'crossbusiness.classes';//'Classes' refers to a facility/service that an establishment or business offers to its guests or visitors in form of instructed classes either at an all-inclusive price, for free, or at a fee.
    case CROSSBUSINESS_CLASSES_FITNESSCLASSES = 'crossbusiness.classes.fitnessclasses';//'Fitness Classes' refers to a facility/service that an establishment or business offers to its guests or visitors in form of instructed fitness classes either at an all-inclusive price, for free, or at a fee.
    case CROSSBUSINESS_CURRENCY_EXCHANGE = 'crossbusiness.currency_exchange';//An establishment or a business offering the exchange of foreign currencies.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS = 'crossbusiness.ev_chargingstations';//EV charging stations refer to the electric vehicle charging station or facility where a person charges their electric vehicle specifically cars.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_CONNECTOR_TYPES = 'crossbusiness.ev_chargingstations.connector_types';//Connector Type is the type of connector plug(s) available at the particular port of an EV Charging Station.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_CONNECTOR_TYPES_CCS1 = 'crossbusiness.ev_chargingstations.connector_types.ccs1';//Charging plug (Connector Type) of type CCS1 for charging of electric vehicle.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_CONNECTOR_TYPES_CCS2 = 'crossbusiness.ev_chargingstations.connector_types.ccs2';//Charging plug (Connector Type) of type CCS2 for charging of electric vehicle.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_CONNECTOR_TYPES_CHA_DE_MO = 'crossbusiness.ev_chargingstations.connector_types.cha_de_mo';//Charging plug (Connector Type) of type CHAdeMO for charging of electric vehicle.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_CONNECTOR_TYPES_GB_T = 'crossbusiness.ev_chargingstations.connector_types.gb_t';//Charging plug (Connector Type) of type GBT1 for charging of electric vehicle.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_CONNECTOR_TYPES_J1772 = 'crossbusiness.ev_chargingstations.connector_types.j1772';//Charging plug (Connector Type) of type J1772 for charging of electric vehicle.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_CONNECTOR_TYPES_MENNEKES = 'crossbusiness.ev_chargingstations.connector_types.mennekes';//Charging plug (Connector Type) of type Mennekes for charging of electric vehicle.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_CONNECTOR_TYPES_TESLA = 'crossbusiness.ev_chargingstations.connector_types.tesla';//Charging plug (Connector Type) of type Tesla for charging of electric vehicle.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_E_BIKE_CHARGERS = 'crossbusiness.ev_chargingstations.e_bike_chargers';//E-bike chargers are the chargers that charges the electric bicyle.
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_EVCHARGING_ONSITE = 'crossbusiness.ev_chargingstations.evcharging_onsite';//An EV charging on-site is a facility that a business or establishment provides to its customers or patrons on-site where they can charge their electric vehicles (EVs).
    case CROSSBUSINESS_EV_CHARGINGSTATIONS_FREE_EV_CHARGING = 'crossbusiness.ev_chargingstations.free_ev_charging';//Free EV Charging is the facility that a business provides where a person can charge their electric vehicle (usually a car) for no charges/fees.
    case CROSSBUSINESS_EVENT_SERVICE = 'crossbusiness.event_service';//An event service is a services that includes, but not limited to, catering, event planning, event supplies, event organization and decoration, entertainment, etc.
    case CROSSBUSINESS_EVENT_SERVICE_KARAOKE = 'crossbusiness.event_service.karaoke';//Karaoke is kind of entertainment where people take turns to sing popular songs into a microphone over prerecorded backing tracks.
    case CROSSBUSINESS_EVENT_SERVICE_PRIVATE_PARTIES = 'crossbusiness.event_service.private_parties';//Business that hosts private parties at their location.
    case CROSSBUSINESS_EVENT_SERVICE_WEDDING_CHAPEL = 'crossbusiness.event_service.wedding_chapel';//A wedding chapel is a place (building or room), where marriages are performed.
    case CROSSBUSINESS_FAMILY_KIDS = 'crossbusiness.family_kids';//Kids refer to the facility that a business or establishment provides to the accompanying children of its customers or patrons.
    case CROSSBUSINESS_FAMILY_KIDS_CHILDCARE = 'crossbusiness.family_kids.childcare';//Childcare refers to the service that a business or establishment provides to its customers/patrons where they look after their children.
    case CROSSBUSINESS_FAMILY_KIDS_GAME_GAMINGROOM = 'crossbusiness.family_kids.game_gamingroom';//Kids Game room is the facility that a business or establishment has where various computerized and friendly games are available for children's entertainment.
    case CROSSBUSINESS_FAMILY_KIDS_HIGHCHAIR = 'crossbusiness.family_kids.highchair';//A high chair is a small chair with long legs for a baby or a small child, which may have an attached try that can be used as a table at mealtime.
    case CROSSBUSINESS_FAMILY_KIDS_KIDS_PLAYAREA = 'crossbusiness.family_kids.kids_playarea';//The 'Kids Play Area' refers to the facility that a business or establishment has, where there is a dedicated area for children to play.
    case CROSSBUSINESS_FAMILY_KIDS_KIDSAMENITIES = 'crossbusiness.family_kids.kidsamenities';//Kids amenities refers to the facility that a business or establishment provides to its customers/patrons where they have various means to entertain children.
    case CROSSBUSINESS_FAMILY_KIDS_KIDSCLUB = 'crossbusiness.family_kids.kidsclub';//Kids club is the facility that a business or establishment has where various social and recreational activities are available for children's entertainment.
    case CROSSBUSINESS_FAMILY_KIDS_PARENTS_WAITINGAREA = 'crossbusiness.family_kids.parents_waitingarea';//The 'parents waiting area' is an area designated for parent(s) to sit and wait while their kid(s) attend a class/activity.
    case CROSSBUSINESS_GOODFOR = 'crossbusiness.goodfor';//Good for refer to the establishment is ‘good for’ kids, singles, family, groups, etc.
    case CROSSBUSINESS_GOODFOR_COUPLES = 'crossbusiness.goodfor.couples';//Good for couples refers to an establishment that is good for people who are couples.
    case CROSSBUSINESS_GOODFOR_FAMILIES = 'crossbusiness.goodfor.families';//Good for families refers to an establishment that is good for people who have kids.
    case CROSSBUSINESS_GOODFOR_GROUPS = 'crossbusiness.goodfor.groups';//Good for groups refer that the establishment is good for people in groups.
    case CROSSBUSINESS_GOODFOR_SINGLES = 'crossbusiness.goodfor.singles';//Good for singles refer that the establishment is good for people who are single.
    case CROSSBUSINESS_HORSEBACKRIDING = 'crossbusiness.horsebackriding';//An establishment offering horseback riding.
    case CROSSBUSINESS_HOSPITALITY = 'crossbusiness.hospitality';//Hospitality is for amenities for a service interaction of facility with the guest. It includes servicing hospitality locations, holding receptions as well as any other area where guests and personnel may interact.
    case CROSSBUSINESS_HOSPITALITY_BANQUET_HALL = 'crossbusiness.hospitality.banquet_hall';//Banquet Hall is a room where large social events like parties, wedding, receptions, ceremonies, etc. are catered.
    case CROSSBUSINESS_HOSPITALITY_BANQUET_SERVICE = 'crossbusiness.hospitality.banquet_service';//Banquet service is a service style for large catered events such as weddings, ceremonies, etc.
    case CROSSBUSINESS_HOSPITALITY_BOOTH_SEATING = 'crossbusiness.hospitality.booth_seating';//Booth Seating is a comfortable, intimate, and semi-enclosed setting where the seating and tables are arranged back-to-back set-up.
    case CROSSBUSINESS_HOSPITALITY_CHESS_AND_CARDROOM = 'crossbusiness.hospitality.chess_and_cardroom';//Chess and Card Room is a facility/room intended solely for playing the game of card and/or chess.
    case CROSSBUSINESS_HOSPITALITY_LOCKER_ROOM = 'crossbusiness.hospitality.locker_room';//A room that contains lockers for the storage of personal belongings and/or space to change clothes (dressing room).
    case CROSSBUSINESS_HOSPITALITY_MULTIFUNCTION_HALL = 'crossbusiness.hospitality.multifunction_hall';//A multifunctional hall is a well-equipped space that can accommodate a wide variety of events or activities.
    case CROSSBUSINESS_HOSPITALITY_PRIVATEROOMS = 'crossbusiness.hospitality.privaterooms';//A private room is a room that can be booked or reserved by a guest to receive the services of a business.
    case CROSSBUSINESS_HOSPITALITY_ROUNDTABLE = 'crossbusiness.hospitality.roundtable';//Roundtable refers to the shape of the table that is round.
    case CROSSBUSINESS_HOSPITALITY_SHIPPING_SERVICE = 'crossbusiness.hospitality.shipping_service';//Shipping Service is a service that a business offers to ship packages and provide postage/materials despite not being a shipping company branch. For example, a hotel offering package drop-off.
    case CROSSBUSINESS_HOSPITALITY_SOFA_SEATING = 'crossbusiness.hospitality.sofa_seating';//A sofa seating refers to a seating that is a soft padded covered furniture usually with armrest and backrest for where two or more people can sit at the same time.
    case CROSSBUSINESS_HOSPITALITY_TERRACE = 'crossbusiness.hospitality.terrace';//A terrace is a paved area or platform next to the structure that is accessible through the main area, public area, or hall area of the business.
    case CROSSBUSINESS_HOSPITALITY_VIP_ROOMS = 'crossbusiness.hospitality.vip_rooms';//A private room reserved for celebrities or important guests only.
    case CROSSBUSINESS_HOSPITALITY_WINDOW_SEATING = 'crossbusiness.hospitality.window_seating';//A seating that faces or is close/next to the window.
    case CROSSBUSINESS_NIGHTLIFE = 'crossbusiness.nightlife';//Nightlife refer that the establishment is good for visiting at the night time.
    case CROSSBUSINESS_NIGHTLIFE_LATENIGHTMEALS = 'crossbusiness.nightlife.latenightmeals';//Late-night meals refer that the establishment serves late-night meals to the customers.
    case CROSSBUSINESS_NIGHTLIFE_LIVEMUSIC = 'crossbusiness.nightlife.livemusic';//Live music refers to music played by a person (or people) in real-time, usually performed with or without a song/words on a musical instrument(s).
    case CROSSBUSINESS_NIGHTLIFE_MUSIC = 'crossbusiness.nightlife.music';//Business attribute related to music.
    case CROSSBUSINESS_NIGHTLIFE_MUSIC_DANCING = 'crossbusiness.nightlife.music.dancing';//Business that includes an section for customers to dance.
    case CROSSBUSINESS_NIGHTLIFE_MUSIC_DJ = 'crossbusiness.nightlife.music.dj';//Business that offers a DJ at their location.
    case CROSSBUSINESS_NIGHTLIFE_MUSIC_JUKEBOX = 'crossbusiness.nightlife.music.jukebox';//Business that has a jukebox.
    case CROSSBUSINESS_NIGHTLIFE_NIGHT_VIEW = 'crossbusiness.nightlife.night_view';//Business offers a scenic view at night.
    case CROSSBUSINESS_NOISE_LEVEL = 'crossbusiness.noise_level';//Business attribute related to the noise level within a business.
    case CROSSBUSINESS_NOISE_LEVEL_QUIET = 'crossbusiness.noise_level.quiet';//Business that maintains a low level of noise.
    case CROSSBUSINESS_PARKING = 'crossbusiness.parking';//A business or establishment that has parking facility.
    case CROSSBUSINESS_PARKING_ACCESSIBLEPARKING = 'crossbusiness.parking.accessibleparking';//A business or establishment that has a parking facility providing mobility options like ramps, lifts, etc. to its customers.
    case CROSSBUSINESS_PARKING_AUTOMATEDPARKING = 'crossbusiness.parking.automatedparking';//Automated Parking is a mechanical multi-story parking garage where cars are parked in vertically stacked formation on multiple floors to maximize the usage of parking space. Such parking garage is installed with a fully automated parking system.
    case CROSSBUSINESS_PARKING_BIKE_PARKING = 'crossbusiness.parking.bike_parking';//Bike parking is a facility that a POI provides at its premises where a visitor can park their bicycle in the dedicated parking.
    case CROSSBUSINESS_PARKING_FREE_SELFPARK = 'crossbusiness.parking.free_selfpark';//Establishment providing the option for visitors or customers to self-park their vehicle during their visit or stay at no cost
    case CROSSBUSINESS_PARKING_MOTORCYCLE_PARKING = 'crossbusiness.parking.motorcycle_parking';//Motorcycle parking is a facility that a business or establishment provides at its premises where visitors can park their motorcycle in the dedicated parking.
    case CROSSBUSINESS_PARKING_OUTDOOR_PARKING = 'crossbusiness.parking.outdoor_parking';//Outdoor Parking is a facility that a business or establishment provides to its patrons, where they can park their vehicles in an open-air facility.
    case CROSSBUSINESS_PARKING_OUTDOOR_PARKING_COVERED_OUTDOOR_PARKING = 'crossbusiness.parking.outdoor_parking.covered_outdoor_parking';//Outdoor covered parking is a facility that a business or establishment provides to its patrons, where they can park their vehicles in a covered/sheltered open-air facility.
    case CROSSBUSINESS_PARKING_OVERSPILL_PARKING = 'crossbusiness.parking.overspill_parking';//Overspill parking is a parking space for vehicles that are parked away from dedicated parking lots.

    case CROSSBUSINESS_PARKING_PAID_PRIVATEPARKING = 'crossbusiness.parking.paid_privateparking';//An establishment that offers paid private parking.
    case CROSSBUSINESS_PARKING_PARKING_GARAGE = 'crossbusiness.parking.parking_garage';//A parking garage is a facility that a business or establishment provides to their customers or patrons, where they can park their vehicles in a building within the dedicated parking space.
    case CROSSBUSINESS_PARKING_PARKING_GARAGE_UNDERGROUND_PARKING = 'crossbusiness.parking.parking_garage.underground_parking';//Underground parking is a facility that a POI has for its customers or patrons, where they can park their vehicles in an underground building/basement within the dedicated parking space.
    case CROSSBUSINESS_PARKING_PARKING_LOT = 'crossbusiness.parking.parking_lot';//Parking Lot is a dedicated area that is only intended for parking of vehicles.
    case CROSSBUSINESS_PARKING_PARKING_LOT_PULLOUT_PARKING = 'crossbusiness.parking.parking_lot.pullout_parking';//An area at the side of a road where drivers may pull-out (or pull-off) for emergencies, to rest, or view the scenery, etc. Typically undeveloped, these parking areas are small cut-outs along a drivable road with space 2 to 20 cars and do not include entry/exit barriers (e.g. gates, swing arms, pay structures, etc)
    case CROSSBUSINESS_PARKING_PARKING_RESTRICTIONS = 'crossbusiness.parking.parking_restrictions';//Parking Restrictions refer to the rules or restrictions in place at a particular parking location.
    case CROSSBUSINESS_PARKING_PARKING_RESTRICTIONS_CUSTOMERPARKING_ONLY = 'crossbusiness.parking.parking_restrictions.customerparking_only';//The parking meant for the customers only is called Customer Parking only.
    case CROSSBUSINESS_PARKING_PARKING_RESTRICTIONS_EVENTPARKING_ONLY = 'crossbusiness.parking.parking_restrictions.eventparking_only';//Event Parking is parking that is available during an event only.
    case CROSSBUSINESS_PARKING_PARKING_RESTRICTIONS_VALETPARKING_ONLY = 'crossbusiness.parking.parking_restrictions.valetparking_only';//Valet Parking is parking where only the attendant (a valet person(s)) parks and retrieves a person's vehicle.
    case CROSSBUSINESS_PARKING_PARKING_RESTRICTIONS_VISITORPARKING_ONLY = 'crossbusiness.parking.parking_restrictions.visitorparking_only';//The parking meant for the visitor only is called Visitor Parking only.
    case CROSSBUSINESS_PARKING_PARKING_VALIDATED = 'crossbusiness.parking.parking_validated';//Business that will validate a parking ticket to reduce or eliminate the cost of parking.
    case CROSSBUSINESS_PARKING_PREMIUMPARKING = 'crossbusiness.parking.premiumparking';//An establishment that offers premium parking services.
    case CROSSBUSINESS_PARKING_REC_VEHICLEPARKING = 'crossbusiness.parking.rec_vehicleparking';//Rec. or Recreational vehicle parking is a facility that a business or establishment provides at its premises where visitors can park their RVs in their parking.
    case CROSSBUSINESS_PARKING_STREETPARKING = 'crossbusiness.parking.streetparking';//Street parking means parking a vehicle on the street, anywhere on or along the curb of streets.
    case CROSSBUSINESS_PARKING_VALETPARKING = 'crossbusiness.parking.valetparking';//Valet Parking is a facility that a business or establishment provides to its patrons where attendants parks and retrieves their vehicles.
    case CROSSBUSINESS_PAYMENTS = 'crossbusiness.payments';//Payments mean paying for the purchases or the services utilized.
    case CROSSBUSINESS_PAYMENTS_APPLEPAY = 'crossbusiness.payments.applepay';//Apple Pay is the facility that a business provides where customers can pay their bills using Apple Pay from their phone.
    case CROSSBUSINESS_PAYMENTS_CASH = 'crossbusiness.payments.cash';//Cash means, a business accepts cash payments from the customers when they shop or avail their services.
    case CROSSBUSINESS_PAYMENTS_CASH_CASH_ONLY = 'crossbusiness.payments.cash.cash_only';//Cash only is referring to a business that accepts cash as only payment method.

    case CROSSBUSINESS_PAYMENTS_CONTACTLESS_PAY = 'crossbusiness.payments.contactless_pay';//Contactless payment is a facility that a business offers to its customer, where they can pay for a purchase, or service without placing or touching their card to a payment machine.
    case CROSSBUSINESS_PAYMENTS_CREDITCARD = 'crossbusiness.payments.creditcard';//A credit card means, that a business accepts payment through credit cards from the customers when they shop or avail their services.
    case CROSSBUSINESS_PAYMENTS_DEBITCARD = 'crossbusiness.payments.debitcard';//A debit card means, that a business accepts payment through debit cards from the customers when they shop or avail their services.
    case CROSSBUSINESS_PAYMENTS_MEMBERCARD = 'crossbusiness.payments.membercard';//A member card means, that a business accepts payment from member-only customers when they shop or avail their services.
    case CROSSBUSINESS_PETS = 'crossbusiness.pets';//Business attributes related to pets
    case CROSSBUSINESS_PETS_PETAMENITIES = 'crossbusiness.pets.petamenities';//A business or establishment that provides facilities or amenities for the pets.
    case CROSSBUSINESS_PETS_PETFEE = 'crossbusiness.pets.petfee';//A business or establishment that charges a customer when a pet is accompanying them.
    case CROSSBUSINESS_PETS_PETS_NOTALLOWED = 'crossbusiness.pets.pets_notallowed';//A business that does allow pets.
    case CROSSBUSINESS_PETS_PETS_WELCOME = 'crossbusiness.pets.pets_welcome';//An business where pets are welcome to come inside the establishment.
    case CROSSBUSINESS_PETS_PETSFREE = 'crossbusiness.pets.petsfree';//A business or establishment that does not charge its customer when a pet is accompanying them and pets can stay for free.
    case CROSSBUSINESS_PETS_PETSITTING_SERVICE = 'crossbusiness.pets.petsitting_service';//Pet sitting is a service that a business provides to its customers who accompany pets, where pets are looked after by the establishment while customers take advantage of the services or the shop.
    case CROSSBUSINESS_PETS_SERVICEANIMALS = 'crossbusiness.pets.serviceanimals';//A business or establishment that allows a Service animal, typically a trained dog, to assist a person with a disability.
    case CROSSBUSINESS_RATES = 'crossbusiness.rates';//This attribute is describing various attributes around pricing, rates, or special offers, etc.
    case CROSSBUSINESS_RATES_ALLINCLUSIVE_RATE = 'crossbusiness.rates.allinclusive_rate';//'All-inclusive rates' means that the indicated rates/price includes all amenity features, or services such as meals and beverages, or the use of a spa, fitness facilities, or classes, etc.
    case CROSSBUSINESS_RESERVATIONS = 'crossbusiness.reservations';//Reservation refers to the action of holding or booking something.
    case CROSSBUSINESS_RESERVATIONS_ACCEPTS_RESERVATIONS = 'crossbusiness.reservations.accepts_reservations';//Accepts Reservation refer to the facility that business or establishment provides where they accept the holding or booking of the service they provide.
    case CROSSBUSINESS_RESERVATIONS_APPOINTMENTS_ONLY = 'crossbusiness.reservations.appointments_only';//Appointment only means where a business or establishment provides its services to the customers on specific time booked by them.

    case CROSSBUSINESS_RESERVATIONS_RESERVATIONS_ONLY = 'crossbusiness.reservations.reservations_only';//Reservation only means where a business or establishment provides its services to the customers only when they book specific time with them.
    case CROSSBUSINESS_RESERVATIONS_WALK_INS = 'crossbusiness.reservations.walk_ins';//Walk-Ins is a facility where a business or establishment provides its services to the customers anytime during business hours when they walk in without any appointments.
    case CROSSBUSINESS_RESTAURANT_ONSITE = 'crossbusiness.restaurant_onsite';//'On-site Restaurant' means a full-service restaurant, or foodservice establishment providing meals to its dining guests at the premises of a hotel or a business only.
    case CROSSBUSINESS_RESTROOMS = 'crossbusiness.restrooms';//Restroom means a bathroom/toilet/water closet (WC).
    case CROSSBUSINESS_RESTROOMS_ACCESSIBLE_RESTROOM = 'crossbusiness.restrooms.accessible_restroom';//Accessible restroom means that the bathroom/toilet/water closet (WC) has facilities to accommodate people with disabilities.
    case CROSSBUSINESS_RESTROOMS_FAMILY_RESTROOM = 'crossbusiness.restrooms.family_restroom';//Family restroom is a unisex bathroom/toilet/water closet (WC) where there are amenities for parents such as changing station, feeding room, children toilet, etc.
    case CROSSBUSINESS_RESTROOMS_FEMALE_RESTROOM = 'crossbusiness.restrooms.female_restroom';//Female restroom means a bathroom/toilet/water closet (WC) specifically for women.
    case CROSSBUSINESS_RESTROOMS_GENDER_NEUTRAL_RESTROOM = 'crossbusiness.restrooms.gender_neutral_restroom';//Gender neutral restroom is a bathroom/toilet/water closet (WC) that is unisex, i.e. it can be used by any person irrespective of their gender or sex.
    case CROSSBUSINESS_RESTROOMS_MALE_RESTROOM = 'crossbusiness.restrooms.male_restroom';//Male restroom means a bathroom/toilet/water closet (WC) specifically for men.
    case CROSSBUSINESS_RESTROOMS_RESTROOM = 'crossbusiness.restrooms.restroom';//Restroom means a bathroom/toilet/water closet (WC).
    case CROSSBUSINESS_SAFETY_FEATURES = 'crossbusiness.safety_features';//Safety implies the safe practices followed by the business.
    case CROSSBUSINESS_SAFETY_FEATURES_COOLING_CENTERS = 'crossbusiness.safety_features.cooling_centers';//Business or location that serves as a cooling center when extreme heat is present in an area.
    case CROSSBUSINESS_SAFETY_FEATURES_CRISIS_SHELTERS = 'crossbusiness.safety_features.crisis_shelters';//Business or location that serves as a place of shelter, often in response to natural disasters.
    case CROSSBUSINESS_SAFETY_FEATURES_FREE_MASKS = 'crossbusiness.safety_features.free_masks';//Free masks is a facility where a business offers free face masks to its customer.
    case CROSSBUSINESS_SAFETY_FEATURES_FREE_SANITIZERS = 'crossbusiness.safety_features.free_sanitizers';//Free hand sanitizer is a facility where a business offers free hand sanitizers to its customer for sanitizing their hands.
    case CROSSBUSINESS_SAFETY_FEATURES_SANITATIONSTATION = 'crossbusiness.safety_features.sanitationstation';//Sanitation Station is a kind of booth facility that a business offers to its customer for sanitizing their hands.
    case CROSSBUSINESS_SAFETY_FEATURES_SANITIZED_FITTING_ROOMS = 'crossbusiness.safety_features.sanitized_fitting_rooms';//The sanitized fitting room is the facility where a business cleans and disinfects fitting rooms for its customers.

    case CROSSBUSINESS_SAFETY_FEATURES_SANITIZED_ROOMS = 'crossbusiness.safety_features.sanitized_rooms';//A business offering sanitized rooms and public areas to its visiting customers.
    case CROSSBUSINESS_SAFETY_FEATURES_SANITIZED_SHOPPING_CARTS = 'crossbusiness.safety_features.sanitized_shopping_carts';//Sanitized shopping cart is the facility where a business provides clean and disinfected shopping carts to its customers.

    case CROSSBUSINESS_SEATING = 'crossbusiness.seating';//Business attribute related to seating at an establishment.
    case CROSSBUSINESS_SEATING_INDOOR_SEATING = 'crossbusiness.seating.indoor_seating';//Business that offers indoor seating.
    case CROSSBUSINESS_SEATING_BOOTH_SEATS = 'crossbusiness.seating.booth_seats';//Booth Seating is a comfortable, intimate, and semi-enclosed setting where the seating and tables are arranged back-to-back set-up.
    case CROSSBUSINESS_SEATING_SOFA_SEATS = 'crossbusiness.seating.sofa_seats';//A sofa seating refers to a seating that is a soft padded covered furniture usually with armrest and backrest for where two or more people can sit at the same time.
    case CROSSBUSINESS_SEATING_WINDOW_SEATS = 'crossbusiness.seating.window_seats';//A seating that faces or is close/next to the window.
    case CROSSBUSINESS_SERVICES = 'crossbusiness.services';//Services refer to amenities offered to clients, guests, or visitors for handling their tasks like deliveries, pickups, storage, providing information, machines for self-service, etc.
    case CROSSBUSINESS_SERVICES_COAT_CHECK = 'crossbusiness.services.coat_check';//Business that offers a coat check which allows a customer to check in personal belongings to be stored in a secure location.
    case CROSSBUSINESS_SERVICES_COUNTER = 'crossbusiness.services.counter';//Business that offers services, typically food, at a counter rather than at a table.
    case CROSSBUSINESS_SERVICES_CURBSIDE_PICKUP = 'crossbusiness.services.curbside_pickup';//Curbside pickup is a service that a business offer to its customers where they can collect their placed orders without stepping out for their vehicle.
    case CROSSBUSINESS_SERVICES_DELIVERY = 'crossbusiness.services.delivery';//Delivery is a service that a business offer to its customers where the business delivers placed orders to the customer’s said location.
    case CROSSBUSINESS_SERVICES_DELIVERY_FREE_DELIVERY = 'crossbusiness.services.delivery.free_delivery';//Free delivery is a service where the placed order of the customer is delivered to them for free.
    case CROSSBUSINESS_SERVICES_DELIVERY_NO_CONTACT_DELIVERY = 'crossbusiness.services.delivery.no_contact_delivery';//No-contact delivery is a service in which the delivery of the purchased product is not directly handed to the customer. The delivery may be left on the door step of the customer's address or at an agreed location.
    case CROSSBUSINESS_SERVICES_DELIVERY_SAME_DAY_DELIVERY = 'crossbusiness.services.delivery.same_day_delivery';//Same-day delivery is a service that a business offers to its customers to receive the merchandise within the same day of placing the order.
    case CROSSBUSINESS_SERVICES_DRIVE_THROUGH = 'crossbusiness.services.drive_through';//Drive-through is a service that a business offers where they serve their customers while they are sitting in their vehicles.
    case CROSSBUSINESS_SERVICES_DRIVE_UP_RETURN = 'crossbusiness.services.drive_up_return';//Drive-up Return is a service that a business offers to its customers to return items (merchandise) from the convenience of their car.
    case CROSSBUSINESS_SERVICES_DROPOFF = 'crossbusiness.services.dropoff';//Drop-off is a service that a business offers where a person can drop-off luggage, merchandise, rental returns, package returns, etc.
    case CROSSBUSINESS_SERVICES_INSTORE_PICKUP = 'crossbusiness.services.instore_pickup';//In-store pickup is a service that a business offers where a customer can collect their online purchased goods from the store/shop/business.
    case CROSSBUSINESS_SERVICES_INSTORE_SHOPPING = 'crossbusiness.services.instore_shopping';//In-store shopping is a service that a business offers where a customer can shop within the store/shop/business.
    case CROSSBUSINESS_SERVICES_LUGGAGE_STORAGE = 'crossbusiness.services.luggage_storage';//A luggage or baggage storage is a service in a hotel or business where guests or visitors can leave their baggage, either for free or at a cost, to collect it later.
    case CROSSBUSINESS_SERVICES_LUGGAGE_STORAGE_COIN_LOCKER = 'crossbusiness.services.luggage_storage.coin_locker';//A coin-operated storage locker is a luggage or baggage storage service that could be available in a hotel, airport, or other business where guests or visitors can store their baggage, tocollect it later.
    case CROSSBUSINESS_SERVICES_PICKUP_DELIVERY_ONLY = 'crossbusiness.services.pickup_delivery_only';//Pickup and or Delivery Only is a service where the purchased product/item can be picked up from the business and or the business will (only) deliver the purchased product/item to the shared address.

    case CROSSBUSINESS_SERVICES_SELF_CHECKOUT = 'crossbusiness.services.self_checkout';//Self-checkout is a service that a business offers where a customer can scan the items by themselves and pay without engaging with employees of the business.
    case CROSSBUSINESS_SERVICES_TAKE_OUT = 'crossbusiness.services.take_out';//Take-out means the food cooked in a restaurant can be packed and eaten by the customer elsewhere.
    case CROSSBUSINESS_SERVICES_TAKE_OUT_ONLY = 'crossbusiness.services.take_out_only';//Take-out only means the food cooked in a restaurant can only be packed and eaten by the customer elsewhere.
    case CROSSBUSINESS_SHOPS = 'crossbusiness.shops';//A shop is a commercial establishment or place of business for people to purchase merchandise.
    case CROSSBUSINESS_SHOPS_GIFTSHOP = 'crossbusiness.shops.giftshop';//A business having a facility for its guests/visitors where there is an area within the establishment that offers the purchase of small gifts and presents.
    case CROSSBUSINESS_SMOKING = 'crossbusiness.smoking';//Smoking means, smoking of tobacco related products.
    case CROSSBUSINESS_SMOKING_SMOKING_ALLOWED = 'crossbusiness.smoking.smoking_allowed';//Smoking allowed means, that smoking of tobacco related products is allowed at the business/establishment.
    case CROSSBUSINESS_SMOKING_SMOKING_AREAS = 'crossbusiness.smoking.smoking_areas';//Smoking area means, that there are designated areas for smoking of tobacco related products at the business/establishment.
    case CROSSBUSINESS_SMOKING_SMOKING_FREE = 'crossbusiness.smoking.smoking_free';//Smoking Free means, that smoking of tobacco related products is not allowed or the business/establishment is non-smoking.
    case CROSSBUSINESS_SPOKEN_LANGUAGES = 'crossbusiness.spoken_languages';//Spoken languages indicates the languages spoken at a business or establishment.
    case CROSSBUSINESS_SPOKEN_LANGUAGES_ENGLISH = 'crossbusiness.spoken_languages.english';//At a business or establishment English language is spoken.
    case CROSSBUSINESS_SPOKEN_LANGUAGES_SPANISH = 'crossbusiness.spoken_languages.spanish';//At a business or establishment Spanish language is spoken.
    case CROSSBUSINESS_SPORT_OUTDOOR = 'crossbusiness.sport_outdoor';//An establishment that offers sports and outdoors services
    case CROSSBUSINESS_SPORT_OUTDOOR_PROSHOP = 'crossbusiness.sport_outdoor.proshop';//An establishment that includes a pro shop, such as for tennis,skiing or golf at a resort or country club.
    case CROSSBUSINESS_SPORT_OUTDOOR_SCENICVIEWERS = 'crossbusiness.sport_outdoor.scenicviewers';//A Scenic Viewer is a telescope or binocular that is permanently mounted on a stalk through which objects are magnified. Usually located at popular tourist places/ scenic views.

    case CROSSBUSINESS_SPORT_OUTDOOR_WATERSTATIONS = 'crossbusiness.sport_outdoor.waterstations';//Water Station means that there is access to water, whether that be water fountains, spigots, etc.
    case CROSSBUSINESS_TECHFEATURES = 'crossbusiness.techfeatures';//The technical feature is a facility like internet services, air-conditioning, etc. that a business offers to its customer.
    case CROSSBUSINESS_TECHFEATURES_110V_SOCKETS = 'crossbusiness.techfeatures.110v_sockets';//Power socket with 110 V (voltage).
    case CROSSBUSINESS_TECHFEATURES_AIRCONDITIONING = 'crossbusiness.techfeatures.airconditioning';//Air Conditioning: A business that offers a facility of maintaining a cool atmosphere in warm conditions to its customers.
    case CROSSBUSINESS_TECHFEATURES_HDTV = 'crossbusiness.techfeatures.hdtv';//HD TV refers to a High-definition television that offers superior picture and audio.
    case CROSSBUSINESS_TECHFEATURES_INTERNET = 'crossbusiness.techfeatures.internet';//A hotel/business that provides internet access to guests/visitors. Use of such service could be for free, paid, or could be part of an all-inclusive package.
    case CROSSBUSINESS_TECHFEATURES_INTERNET_FREEINTERNET = 'crossbusiness.techfeatures.internet.freeinternet';//A hotel/business that provides internet access to guests/visitors for free.
    case CROSSBUSINESS_TECHFEATURES_INTERNET_HIGH_SPEED_INTERNET = 'crossbusiness.techfeatures.internet.high_speed_internet';//High-speed Internet is an amenity that is provided by a hotel/business to guests or visitors.
    case CROSSBUSINESS_TECHFEATURES_PORTABLECHARGER = 'crossbusiness.techfeatures.portablecharger';//A portable charger is a reusable battery that can be carried along to charge devices like phones and laptops on go.
    case CROSSBUSINESS_TECHFEATURES_WIFI = 'crossbusiness.techfeatures.wifi';//Wi-Fi is a facility of wireless internet that a business offers to its customer.
    case CROSSBUSINESS_TECHFEATURES_WIFI_FREEWIFI = 'crossbusiness.techfeatures.wifi.freewifi';//Free Wi-Fi is a facility of wireless internet that a business offers to its customer for free.
    case CROSSBUSINESS_TRANSPORTATION = 'crossbusiness.transportation';//Transportation is a facility that a business or establishment provides to its customers or patrons, where they are transported from one place to another by some means.
    case CROSSBUSINESS_TRANSPORTATION_ELEVATOR = 'crossbusiness.transportation.elevator';//An elevator is a facility that a business or establishment provides to its customers or patrons to travel from one floor to another within the building.
    case CROSSBUSINESS_TRANSPORTATION_FREE_AIRPORTSHUTTLE = 'crossbusiness.transportation.free_airportshuttle';//A free airport shuttle is a scheduled regular transportation facility that a business or establishment provides to its customers or patrons to travel between the airport and business/establishment.
    case CROSSBUSINESS_TRANSPORTATION_SHUTTLE = 'crossbusiness.transportation.shuttle';//A shuttle is a scheduled regular transportation facility that a business or establishment provides to its customers or patrons to travel between two or multiple places.
    case CROSSBUSINESS_WATERSKIING = 'crossbusiness.waterskiing';//An establishment offering waterskiing activities.
    case DINING = 'dining';//Dining means a place to eat a meal.
    case DINING_CASUALDINING = 'dining.casualdining';//Casual dining means a restaurant that offers regular meal in an casual atmosphere to their dining guests.
    case DINING_CATERING_SERVICE = 'dining.catering_service';//'Catering service' means a business providing a service where it prepares meals and caters to groups of any size, and/or for dining in a private or external place and events.
    case DINING_ENGLISH_MENU = 'dining.english_menu';//English menu means the establishment has a menu card or menu information in the English language for its guests.
    case DINING_FINEDINING = 'dining.finedining';//Fine dining means a restaurant that offers a full-service restaurant with specific meal courses. These are high-quality restaurants and may have some rules for dining guests.
    case DINING_MEALOPTIONS = 'dining.mealoptions';//"Meal options" refers to a list of menu types a food establishment is serving at various times of the day.
    case DINING_MEALOPTIONS_ALL_YOU_CAN_DRINK = 'dining.mealoptions.all_you_can_drink';//All you can drink means that the food establishment provides unlimited amount of drink (including alcoholic and/or non-alcoholic) on a fixed price to its guests.
    case DINING_MEALOPTIONS_ALL_YOU_CAN_EAT = 'dining.mealoptions.all_you_can_eat';//All you can eat means that the food establishment provides unlimited amount of food on a fixed price to its guests.
    case DINING_MEALOPTIONS_BREAKFAST = 'dining.mealoptions.breakfast';//Breakfast means that the food service establishment provides breakfast meals to its dining guests.
    case DINING_MEALOPTIONS_BRUNCH = 'dining.mealoptions.brunch';//Brunch means that the food service establishment provides brunch meals to its dining guests.
    case DINING_MEALOPTIONS_BUFFET = 'dining.mealoptions.buffet';//Buffet means that the food service establishment provides meals in form of buffet to its dining guests.
    case DINING_MEALOPTIONS_DESSERT = 'dining.mealoptions.dessert';//Dessert means the sweet dish or sweet course that is eaten/served at the end of a meal.
    case DINING_MEALOPTIONS_DINNER = 'dining.mealoptions.dinner';//Dinner means that the food service establishment provides dinner meals to its dining guests.
    case DINING_MEALOPTIONS_KIDSEATFREE = 'dining.mealoptions.kidseatfree';//Kids eat free means that the food service establishment provides free meals for kids to its dining guests.
    case DINING_MEALOPTIONS_KIDSMENU = 'dining.mealoptions.kidsmenu';//Kids menu means that the food service establishment have kids menu for its dining guests.
    case DINING_MEALOPTIONS_LUNCH = 'dining.mealoptions.lunch';//Lunch means that the food service establishment provides lunch meals to its dining guests.
    case DINING_MEALPLAN = 'dining.mealplan';//'Meal Plans' also known as dining plans are a special type of tariff where room tariff (rate) is packaged with various meal combinations.
    case DINING_ONSITE_COFFEESHOP = 'dining.onsite_coffeeshop';//On-site coffee shop refers to a facility contained within another business, serving primarily coffee and hot beverages along with light snacks.
    case DINING_OUTDOORDINING = 'dining.outdoordining';//Outdoor dining means the eating area with seats and/or tables located outdoors of a food service establishment.
    case DINING_OUTDOORDINING_COVERED_OUTDOORDINING = 'dining.outdoordining.covered_outdoordining';//Outdoor Covering Dining means that the food service establishment's outdoor dining space is covered with mounted fixtures.
    case DINING_OUTDOORDINING_HEATED_OUTDOORDINING = 'dining.outdoordining.heated_outdoordining';//'Outdoor heated dining' means that the food service establishment's outdoor dining space has features or appliances to keep the dining area warm for the customers.
    case DINING_OUTDOORDINING_OUTDOOR_DINING = 'dining.outdoordining.outdoor_dining';//Outdoor dining means the eating area with seats and/or tables located outdoors of a food service establishment.
    case DINING_SPECIALDIETS = 'dining.specialdiets';//Special diet dining is a facility where a food service establishment provides meals according to special dietary needs for their dining guests.
    case DINING_SPECIALDIETS_DAIRYFREE = 'dining.specialdiets.dairyfree';//‘Dairy free’ means that a food service establishment has dairy-free meal options for its dining guests.
    case DINING_SPECIALDIETS_GLUTENFREE = 'dining.specialdiets.glutenfree';//‘Gluten free’ means that a food service establishment has gluten-free meal options for its dining guests.
    case DINING_SPECIALDIETS_HALAL = 'dining.specialdiets.halal';//‘Halal' means that a food service establishment has halal meal options for its dining guests.
    case DINING_SPECIALDIETS_KOSHER = 'dining.specialdiets.kosher';//‘Kosher’ means that a food service establishment has kosher meal options for its dining guests.
    case DINING_SPECIALDIETS_VEGAN = 'dining.specialdiets.vegan';//‘Vegan’ means that a food service establishment has vegan meal options for its dining guests.
    case DINING_SPECIALDIETS_VEGETARIAN = 'dining.specialdiets.vegetarian';//‘Vegetarian’ means that a food service establishment has vegetarian meal options for its dining guests.
    case DINING_TAKEOUT = 'dining.takeout';//Take-out means the food cooked in a restaurant can be packed and eaten by the customer elsewhere.
    case HOTEL = 'hotel';//A facility where short-term lodging is possible.
    case HOTEL_BELL_DESK = 'hotel.bell_desk';//A small desk with an attendant that provides services like luggage handling, paging, mail and message handling, deliveries, and answering queries, etc. of the staying guests.
    case HOTEL_BREAKFASTCHOICE = 'hotel.breakfastchoice';//The breakfast choice means that the establishment has a range of breakfast food for its guests.
    case HOTEL_BREAKFASTCHOICE_ALLDAY_BREAKFAST_CHOICE = 'hotel.breakfastchoice.allday_breakfast_choice';//'All Day breakfast' means that a hotel provides breakfast meals to its dining guests though out the day.
    case HOTEL_BREAKFASTCHOICE_CONTINENTALBREAKFAST_CHOICE = 'hotel.breakfastchoice.continentalbreakfast_choice';//The continental breakfast means that a hotel provides continental breakfast meals to its dining guests.
    case HOTEL_BREAKFASTCHOICE_ENGLISHBREAKFAST_CHOICE = 'hotel.breakfastchoice.englishbreakfast_choice';//English breakfast means that a hotel provides English breakfast meals to its dining guests.
    case HOTEL_BREAKFASTCHOICE_FREEBREAKFAST_CHOICE = 'hotel.breakfastchoice.freebreakfast_choice';//Free breakfast means that a hotel provides free breakfast meals to its dining guests.
    case HOTEL_BREAKFASTCHOICE_FULLBREAKFAST_CHOICE = 'hotel.breakfastchoice.fullbreakfast_choice';//A full breakfast means that a hotel provides for full breakfast meals to its dining guests.
    case HOTEL_BUSINESSCENTER = 'hotel.businesscenter';//A business center is a facility that allows the guest to work during their stay. Business Centers can offer wide ranges of services like conferences, meetings, exhibitions, seminars, etc. to their corporate guests.
    case HOTEL_BUSINESSCENTER_BUSINESS_CENTER = 'hotel.businesscenter.business_center';//A business center is a facility that allows the guest to work during their stay. Business Centers can offer wide ranges of services like conferences, meetings, exhibitions, seminars, etc. to their corporate guests.
    case HOTEL_BUSINESSCENTER_COMPUTER_EQUIPMENT = 'hotel.businesscenter.computer_equipment';//A hotel offering computer equipment such as laptops, desktops, etc. to its guests either for free or at a charge.
    case HOTEL_BUSINESSCENTER_MEETINGROOMS = 'hotel.businesscenter.meetingrooms';//Meeting rooms are an amenity/facility that allows the guests to organize their meetings at the same place of their stay.
    case HOTEL_FRONTDESK = 'hotel.frontdesk';//The front desk, also called front offce or reception area, is the place where guests first arrive in a hotel. It is usually staffed with a receptionist, who will confirm a reservation, assist with the check-in/check-out process, as well as other services related to the stay. 
    case HOTEL_HOTELCLASS = 'hotel.hotelclass';//Hotel Class means the classifications or ratings of the establishment which are based on the industry standards.
    case HOTEL_LOCATION = 'hotel.location';//Location refers to a particular place or position of a business.
    case HOTEL_LOCATION_BEACHFRONT = 'hotel.location.beachfront';//A beachfront location refers to the location of a business/establishment where it either on or adjacent to a beach.
    case HOTEL_LOCATION_CENTRALLOCATION = 'hotel.location.centrallocation';//Centrally located refer to the location of the business in or close to the town/city center.
    case HOTEL_LOCATION_WATERFRONT = 'hotel.location.waterfront';//Waterfront location refers to the location of a business/establishment where it either on or adjacent to a water edge.
    case HOTEL_PROPERTY_AMENITY = 'hotel.property_amenity';//A hotel amenity is a desirable or useful feature provided when staying at a hotel, motel, or other places of lodging. In some places of lodging, certain property amenities may be standard with all rooms. In others, they may be optional for an additional cost.
    case HOTEL_PROPERTY_AMENITY_BICYCLE_RENTAL = 'hotel.property_amenity.bicycle_rental';//'Bicycle Rental' refers to the facility that a business features where the bicycles can be rented on-site for free or at a charge.
    case HOTEL_PROPERTY_AMENITY_CAR_RENTAL_SERVICES = 'hotel.property_amenity.car_rental_services';//'Car Rental Service' refers to the facility that a hotel or a business features for its guests/visitors where the car rentals are available on-site at a surcharge.
    case HOTEL_PROPERTY_AMENITY_CONCIERGESERVICES = 'hotel.property_amenity.conciergeservices';//Concierge service is a facility that supports the guests by performing various tasks such as restaurant reservations, booking hotels, organizing transportations, booking and recommending activities, coordinating events, etc.
    case HOTEL_PROPERTY_AMENITY_FRONT_DESK = 'hotel.property_amenity.front_desk';//The front desk, also called front offce or reception area, is the place where guests first arrive in a hotel. It is usually staffed with a receptionist, who will confirm a reservation, assist with the check-in/check-out process, as well as other services related to the stay. 
    case HOTEL_PROPERTY_AMENITY_FRONT_DESK_24H_FRONT_DESK = 'hotel.property_amenity.front_desk.24h_front_desk';//A 24 Hours front desk also known as 24 hours (h) front office or reception area, is the place where guests first arrive in a hotel. It is usually staffed with a receptionist, who confirms the reservations, assists with the check-in/check-out process, as well as other services related to the stay. 24-Hour Front desk meaning the Front Desk services/feature is available all day.
    case HOTEL_PROPERTY_AMENITY_GOLFCOURSE = 'hotel.property_amenity.golfcourse';//A hotel or a business that features having a golf course or golf club at its premises or affiliated with some golf course or golf club business.
    case HOTEL_PROPERTY_AMENITY_HOUSEKEEPING = 'hotel.property_amenity.housekeeping';//Housekeeping is a service where staff members of the business performing daily duties such as cleaning guest rooms, public areas, restocking in-room amenities such as linens, soap products, towels, and food or drink items usually, at a surcharge.
    case HOTEL_PROPERTY_AMENITY_ICEMACHINE = 'hotel.property_amenity.icemachine';//An ice dispenser machine where a guest can fill their buckets of ice for their room.
    case HOTEL_PROPERTY_AMENITY_LAUNDRY = 'hotel.property_amenity.laundry';//A hotel or a business featuring a laundry facility either equipped with free or coin-operated appliances or in form of a full-service dry cleaning amenity, usually at a surcharge.

    case HOTEL_PROPERTY_AMENITY_LAUNDRY_DRYCLEANING_SERVICE = 'hotel.property_amenity.laundry.drycleaning_service';//Dry cleaning is a laundry service available for the guests within the premises of the business.
    case HOTEL_PROPERTY_AMENITY_LAUNDRY_FULL_LAUNDRYSERVICE = 'hotel.property_amenity.laundry.full_laundryservice';//A full laundry service means a facility that the business offers to its guests for a surcharge.
    case HOTEL_PROPERTY_AMENITY_LAUNDRY_LAUNDROMAT = 'hotel.property_amenity.laundry.laundromat';//Laundromat means a facility that is available at the business for the shared use of guests, at a small fee, that is either payable at the front desk or at the appliance itself.
    case HOTEL_PROPERTY_AMENITY_LAUNDRY_LAUNDRYROOM = 'hotel.property_amenity.laundry.laundryroom';//A designated room at a business for the guests to wash their clothes in shared appliances usually free of charge. The laundry room is equipped with both a washer and a dryer and may have a small space for folding washing.
    case HOTEL_PROPERTY_AMENITY_NIGHTCLUB_ONSITE = 'hotel.property_amenity.nightclub_onsite';//A hotel featuring a nightclub onsite, focused on music, dancing and adult entertainment. The access to night club could be for free, paid or could be part of an all-inclusive package - no cover fee.
    case HOTEL_PROPERTY_AMENITY_ONSITE_FIREPIT = 'hotel.property_amenity.onsite_firepit';//A self contained structure for supporting a fire.
    case HOTEL_PROPERTY_AMENITY_ONSITE_SHOPPING = 'hotel.property_amenity.onsite_shopping';//An onsite shopping is a convenience where the guest can shop within the premises of their stay.
    case HOTEL_PROPERTY_AMENITY_ONSITE_SHOPPING_GIFT_SHOP = 'hotel.property_amenity.onsite_shopping.gift_shop';//A business having a facility for its guests/visitors where there is an area within the establishment that offers the purchase of small gifts and presents.
    case HOTEL_PROPERTY_AMENITY_SCUBA_ONSITE = 'hotel.property_amenity.scuba_onsite';//A hotel featuring a scuba dive center on-site. Scuba centers offer lessons as well as the rental of scuba or snorkeling gear.
    case HOTEL_PROPERTY_AMENITY_SKI_IN_OUT = 'hotel.property_amenity.ski_in_out';//Ski-in, Ski-out means that the business is on a mountain with direct access to the ski slopes.
    case HOTEL_PROPERTY_AMENITY_SKICONCIERGE = 'hotel.property_amenity.skiconcierge';//A ski concierge is a facility that a business offers to its guests/visitors where the business handles all the arrangements from ski-gear to ski-related activities.
    case HOTEL_PROPERTY_AMENITY_SNORKELING = 'hotel.property_amenity.snorkeling';//A hotel featuring snorkeling activities for their guests, and usually the rental of snorkeling equipment, such as masks, snorkels and fins.
    case HOTEL_PROPERTY_AMENITY_SWIMMINGPOOL = 'hotel.property_amenity.swimmingpool';//A swimming pool to the business, is available as a facility to the guests or tenants of the building.
    case HOTEL_PROPERTY_AMENITY_SWIMMINGPOOL_ACCESSIBLE_HOTTUB = 'hotel.property_amenity.swimmingpool.accessible_hottub';//An accessible hot tub is referring to a jacuzzi or hot tub for guests with physical impairments, outside of a room setting.

    case HOTEL_PROPERTY_AMENITY_SWIMMINGPOOL_ACCESSIBLE_POOL = 'hotel.property_amenity.swimmingpool.accessible_pool';//An accessible pool means a swimming pool with an access facility for the guests with physical impairments.

    case HOTEL_PROPERTY_AMENITY_SWIMMINGPOOL_HOTTUB = 'hotel.property_amenity.swimmingpool.hottub';//Hot tub refers to a hot tub or jucuzzi that is available to guests outside of a room setting.
    case HOTEL_PROPERTY_AMENITY_SWIMMINGPOOL_KIDSPOOL = 'hotel.property_amenity.swimmingpool.kidspool';//A swimming pool especially for kids belonging to the business, is available as a facility to the guest's children or tenants children of the building.
    case HOTEL_PROPERTY_AMENITY_TENNISCOURT = 'hotel.property_amenity.tenniscourt';//A rectangular area marked with lines where tennis can be played within the premises of the business.
    case HOTEL_PROPERTY_AMENITY_WATERPARK = 'hotel.property_amenity.waterpark';//A water park is an entertainment amenity of a hotel or resort, featuring water play areas such as swimming pools, water slides, splash pads, water playgrounds, and lazy rivers, as well as areas for floating, bathing, swimming, and other barefoot water-related environments.
    case HOTEL_ROOM = 'hotel.room';//Amenities available in the guest room(s).
    case HOTEL_ROOM_ACCESSIBLEROOM = 'hotel.room.accessibleroom';//Accessible rooms mean that the room or rooms of a hotel, motel, inn, resort, or multi-tenant buildings like apartments are wheelchair accessible.
    case HOTEL_ROOM_BALCONY = 'hotel.room.balcony';//A balcony is a platform enclosed by a wall or railing (balustrade) on the outside of the room that can only be accessed from the given room.
    case HOTEL_ROOM_COFFEE_TEA_MAKER = 'hotel.room.coffee_tea_maker';//A room equipped with a coffee or tea maker and sometimes complimentary supplies for guests to enjoy during their stay.
    case HOTEL_ROOM_CONNECTINGROOM = 'hotel.room.connectingroom';//A connecting room is facility where two adjoining rooms are connected by a locked door between them.
    case HOTEL_ROOM_CRIB = 'hotel.room.crib';//A crib or cot is the bed for a young child that is available to the guest on request for extra charges.
    case HOTEL_ROOM_CRIB_FREE_CRIB = 'hotel.room.crib.free_crib';//A crib or cot is the bed for a young child that is available to the guest on request for no extra charges.
    case HOTEL_ROOM_FREE_NEWSPAPER = 'hotel.room.free_newspaper';//Free newspaper means a complimentary service where a newspaper gets delivered to the staying guests.
    case HOTEL_ROOM_FREE_SHOESHINE = 'hotel.room.free_shoeshine';//Free shoe shine means that a complimentary mini shoe polish set is available in the room of the staying guests.
    case HOTEL_ROOM_HAIRDRYER = 'hotel.room.hairdryer';//A room equipped with a hairdryer for guests to use during their stay.
    case HOTEL_ROOM_IRON = 'hotel.room.iron';//An amenity in which a room is equipped with an iron and usually ironing board for guests to use during their stay.
    case HOTEL_ROOM_KIDS_STAY_FREE = 'hotel.room.kids_stay_free';//Kids stay free is a facility that allows accompanying children of the guest to stay free of charge with their parents.
    case HOTEL_ROOM_KITCHENETTE = 'hotel.room.kitchenette';//A 'Kitchenette' is a small cooking area within a guest room where a guest can cook or warm the meals during their stay.
    case HOTEL_ROOM_MICROWAVE = 'hotel.room.microwave';//A room is equipped with a microwave for guests to use during their stay.
    case HOTEL_ROOM_MINIBAR = 'hotel.room.minibar';//A 'Minibar' is a facility in a guest room which is a small refrigerator that can be empty or fully stocked with alcoholic or non-alcoholic drinks and snacks for purchase.
    case HOTEL_ROOM_NON_SMOKINGROOM = 'hotel.room.non_smokingroom';//A hotel featuring designated non-smoking rooms in which the use of cigarettes or tobacco is prohibited.
    case HOTEL_ROOM_PULLOUT_SOFA = 'hotel.room.pullout_sofa';//A pullout sofa is a sofa present in the guest room that can be converted into a bed.
    case HOTEL_ROOM_ROLLAWAY = 'hotel.room.rollaway';//Rollaway is a mattress on a foldable or rollable frame that can be easily setup as a bed when needed.
    case HOTEL_ROOM_ROLLAWAY_FREE_ROLLAWAY = 'hotel.room.rollaway.free_rollaway';//Rollaway is a mattress on a foldable or rollable frame that can be easily setup as a bed when needed for free of charge.
    case HOTEL_ROOM_ROOMSAFE = 'hotel.room.roomsafe';//A Room Safe refers to a small locker or a safety box within the guest room where they can secure their valuables.
    case HOTEL_ROOM_ROOMSERVICE = 'hotel.room.roomservice';//Room service is a service that allows guests to order food and drinks to be bought to their rooms.
    case HOTEL_ROOM_ROOMSERVICE_24H_ROOMSERVICE = 'hotel.room.roomservice.24h_roomservice';//24 hours Room service is a service that allows guests to order food and drinks to be bought to their rooms at any time of the day.
    case HOTEL_ROOM_SMOKINGROOM = 'hotel.room.smokingroom';//A smoking room means that the establishments have a guest room(s) that allows the guest to smoke within the room only.
    case HOTEL_ROOM_SUITE = 'hotel.room.suite';//A 'Suite' is the class of room accommodation that usually has more space and amenity features as compared to the standard room.
    case HOTEL_ROOM_TELEVISION = 'hotel.room.television';//A room equipped with a television (TV) for the entertainment of their guests during a stay.
    case HOTEL_ROOM_VIEW = 'hotel.room.view';//Room view refers to the view from the room where it is located.
    case HOTEL_ROOM_VIEW_CITY_VIEW = 'hotel.room.view.city_view';//Room with a view of city.
    case HOTEL_ROOM_VIEW_MOUNTAIN_VIEW = 'hotel.room.view.mountain_view';//Room with a view of mountains, hills, or valley.
    case HOTEL_ROOM_VIEW_POOL_VIEW = 'hotel.room.view.pool_view';//Room with a view of pool.
    case HOTEL_ROOM_VIEW_WATER_VIEW = 'hotel.room.view.water_view';//A room with a view of water body or beach.
    case HOTEL_ROOM_WAKEUP_SERVICE = 'hotel.room.wakeup_service';//Wakeup service is a service that allows guests to request a telephone call at a pre-specified time at the front desk or reception of the business.
    case HOTEL_ROOM_WASHER_DRYER = 'hotel.room.washer_dryer';//This room amenity specifies that a there are washer and dryer available in a guest room or rooms.
    case HOTEL_WELLNESS = 'hotel.wellness';//Amenities like gym, yoga, etc. are available to supports the fitness and health of the staying guests.
    case HOTEL_WELLNESS_FITNESSCENTER = 'hotel.wellness.fitnesscenter';//A fitness center is an amenity or a facility that contain special equipment where guests can go and exercise.
    case HOTEL_WELLNESS_HAIRSALON = 'hotel.wellness.hairsalon';//'Hair Salon' is a facility where a full-service hair salon is available on-site or within the hotel property.
    case HOTEL_WELLNESS_HEALTHCLUB = 'hotel.wellness.healthclub';//A health club is an amenity that offers facilities of exercise and beauty treatments to the staying guests.
    case HOTEL_WELLNESS_SPA = 'hotel.wellness.spa';//A spa is a facility where guests can receive individual services or treatments using the facilities like steam, sauna, massage, etc.
    case HOTEL_WELLNESS_SPA_BATH = 'hotel.wellness.spa.bath';//Bath refers to the large communal bathing area/bathhouse facility where a person specifically go for bath
    case HOTEL_WELLNESS_SPA_BATH_HOT_SPRING = 'hotel.wellness.spa.bath.hot_spring';//Bathhouse or bath facility with a natural hot spring or has water that is sourced directly from a natural hot spring.
    case HOTEL_WELLNESS_SPA_JACUZZI = 'hotel.wellness.spa.jacuzzi';//A jacuzzi is an amenity within the spa where the hot water jet is available for guest's pleasure.
    case HOTEL_WELLNESS_SPA_MASSAGE_SERVICE = 'hotel.wellness.spa.massage_service';//A 'Massage Service' is a kind of spa service that is offered to the guests/visitors either for a surcharge or included in a pre-booked spa package.
    case HOTEL_WELLNESS_SPA_SAUNA = 'hotel.wellness.spa.sauna';//A sauna is an enclosed room with a dry heat facility that can be utilized by the guests for pleasure.
    case HOTEL_WELLNESS_SPA_STEAMROOM = 'hotel.wellness.spa.steamroom';//A 'steam room' is an enclosed space that is heated with steam which can be utilized by the guests for pleasure.
    case MEDICALCARE = 'medicalcare';//Business attributes related to medical care.
    case MEDICALCARE_INSURANCE = 'medicalcare.insurance';//Business attribute related to insurance.
    case MEDICALCARE_INSURANCE_ACCEPTS_INSURANCE = 'medicalcare.insurance.accepts_insurance';//Business that accepts insurance for its services.
    case MEDICALCARE_TESTING = 'medicalcare.testing';//Business attributes related to medical testing.
    case MEDICALCARE_TESTING_COVID_19_TESTING = 'medicalcare.testing.covid_19_testing';//Business that offers COVID-19 testing on site.
    case MEDICALCARE_VACCINATIONS = 'medicalcare.vaccinations';//Business attributes related to health vaccinations.
    case MEDICALCARE_VACCINATIONS_COVID_19_VACCINES = 'medicalcare.vaccinations.covid_19_vaccines';//Business that offers COVID-19 vaccines on site.
    case MEDICALCARE_WOMENS_HEALTH = 'medicalcare.womens_health';//An attribute related to Women's Health
    case MEDICALCARE_WOMENS_HEALTH_ABORTION_PROVIDER = 'medicalcare.womens_health.abortion_provider';//A business that provides abortion services.
    case RETAIL = 'retail';//Retail is the facility where goods or services are sold or provided to the buyers for their use or consumption.
    case RETAIL_APPLE = 'retail.apple';//Retail Apple is a facility in a business or establishment other than the Apple Store that is authorized to sell Apple products.
    case RETAIL_APPLE_APPLE_SHOP = 'retail.apple.apple_shop';//Apple Shop is a dedicated section within a business authorized to sell Apple products, and supported by especially trained personnel.
    case RETAIL_APPLE_AUTHORIZED_SERVICE = 'retail.apple.authorized_service';//Authorized service is a facility where a business is certified or authorized to provide services to Apple customers.
    case RETAIL_APPLE_CERTIFIED_REPAIR = 'retail.apple.certified_repair';//Apple-certified repair is a facility where a business or establishment other than an Apple Store is certified to repair Apple products.
    case RETAIL_APPLE_DEVICE_TRADEIN = 'retail.apple.device_tradein';//Device trade-in is a facility where a business provides trading in of old Apple devices for credit.
    case RETAIL_APPLE_GENIUSBAR_WALKIN = 'retail.apple.geniusbar_walkin';//The Genius bar walk-in is the facility where customers can walk in at any time during business hours to get technical support from the experts.
    case RETAIL_APPLE_SMALLBIZ_SOLUTION = 'retail.apple.smallbiz_solution';//Small Business Solutions is a facility where small business owners can obtain technical solutions for their day to day business activities.
    case RETAIL_APPLE_TODAY_SESSION = 'retail.apple.today_session';//Today session means ‘Today at Apple Sessions’ facility is provided at the business.
    case RETAIL_SPECIALEVENTS = 'retail.specialevents';//A special event is a facility where an establishment or business organizes exclusive retail events for its customers.

    public function jsonSerialize(): string{
        return $this->value;
    }
}
